### ISSUE TITLE
training 

### ISSUE THREAD

**Issue by johndpope** [hologerry/IMF#5]
Hi @hologerry  

was hoping to hace this IMF stuff all done - so i can move onto stable diffusion stuff - but have one last snag during training.

Most recently (just yesterday) I aligned my resblock models most closely to LIA and quality of image generation is now fantastic.
God knows how they reached this code - so esoteric. 

I have this trouble though with model where it is too hard for it to transition videos....
https://wandb.ai/snoozie/IMF/runs/nh3zc28s?nw=nwusersnoozie

just kinda falls over
I add in a lot of bandaid code - but not sure ...

<img width="1353" alt="Screenshot 2024-09-03 at 9 43 23 pm" src="https://github.com/user-attachments/assets/05a7fd6e-e56a-4bb9-bb74-a2998435d25e">
<img width="1314" alt="Screenshot 2024-09-03 at 9 43 10 pm" src="https://github.com/user-attachments/assets/e927293a-4bef-4e28-8945-81dbb56a8318">

<img width="1364" alt="Screenshot 2024-09-03 at 9 43 29 pm" src="https://github.com/user-attachments/assets/d226b6dd-676a-4d3a-8f0f-98b2f69f4441">

```shell
/media/2TB/IMF/helper.py:172: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all axes decorations.
  plt.tight_layout()
Epoch 1/1000:   5%|███▌                                                                        | 3/64 [31:03<10:31:17, 620.95s/it, G Loss=4.2244, D Loss=3.4075]👿👿👿 Warning: All gradients are zero. 👿👿👿
Traceback (most recent call last):
  File "/media/2TB/IMF/train.py", line 451, in <module>
    main()
  File "/media/2TB/IMF/train.py", line 448, in main
    trainer.train()
  File "/media/2TB/IMF/train.py", line 323, in train
    log_grad_flow(self.model.named_parameters(),global_step)
  File "/media/2TB/IMF/helper.py", line 159, in log_grad_flow
    raise ValueError(f"👿👿👿 Warning: All gradients are zero. 👿👿👿")
ValueError: 👿👿👿 Warning: All gradients are zero. 👿👿👿

```

someone mentioned i need higher batch size - 
https://github.com/johndpope/IMF/issues/25

is it true? can model not converge with lower batch size?

My code is taking a video / or image folder from a video - and cycle through - frame by frame with one reference image.
https://github.com/johndpope/IMF/blob/main/train.py#L286

I'm currenly able to get batch size to 4 on a a100 - 40gb -  but it still falls over.

there's a way to fudge this with accumulation steps - so the loss is reduced 
with 2 videos im at 15-20 gb of vram

JP

**Comment by johndpope** [comment]
i think i found problem with problematic learning rates - 
still interested to hear thoughts on batch size
